disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_imports
  - unused_import

line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_comments: true

force_unwrapping:
  severity: warning

implicitly_unwrapped_optional:
  severity: warning

missing_docs:
  severity: warning
  excludes_inherited_types: true

excluded:
  - Pods
  - .build
  - DerivedData
  - GRWMStudio/Resources
